### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by matkoniecz** [PhoenixDD/Cheapest-Flights-bot#2]
See https://choosealicense.com/ for tl;dr and to confirmation that it is a real problem

Currently no license is mentioned anywhere, what makes this code fully copyrighted. This is a default for any creative work - what includes software.

Please, please add a license. The fact none is listed makes using this software a legal quagmire.

For start - people are not allowed to make pull requests with improvements as it would require ditribution of modified code - that is fully copyrighted.

For example currently it is not legal to use, improve or distribute this code. Hopefully this is not the intended effect, given that code was open sources.

In case that for some reason not releasing it under open license is intentional - mentioning it in the readme also would be a good idea. Though note that given that it is open sourced it will not stop anyone not caring about copyrights.

Popular licences include:

 - MIT license that allows people to use code for any purpose
 - GNU GPLv3 that intends to allow everything but to block people from distributing closed source versions that build on open source project

Feel free to ask me questions :) I know and understand that people often prefer to ignore copyright law, unfortunately it will not make it disappear.

**Comment by PhoenixDD** [comment]
Thank you for your concern, I have added the License
